setting:
  # Core params - note all resampling is done in quantus
  padDistance: 5
  preCrop: true
  binWidth: 1     # NEVER MODIFY THIS VALUE - binning is completed manually in quantus
  
  # Params to optimize
  weightingNorm: # None / no weighting
  distances: [1]

# Image types to use: “Original” for unfiltered image, for possible filters, see documentation.
imageType:
  Original: {}
  # LoG:
  #   sigma: [1.0, 2.0, 3.0]
  # Wavelet: {}
  # Square: {}
  # Exponential: {}
  # Gradient: {}
  # LBP3D: {}

featureClass:
  # shape:
  # firstorder: - not needed because of normalization and not TTC
  glcm:  # Disable SumAverage by specifying all other GLCM features available
  glrlm:
  glszm:
  gldm:
  ngtdm: