# Screen 1: Scan loader
scan_loader: nifti

# Screen 2: Scan inputs
scan_path: PLACEHOLDER
scan_loader_kwargs:

# Screen 3: Segmentation (either drawing or saved)
seg_path: PLACEHOLDER
seg_loader: PLACEHOLDER
seg_loader_kwargs:
  assert_scan: False
  assert_phantom: False

# Screen 4: Analysis
analysis_type: ttc_curves
analysis_kwargs:
  curves_output_path: PLACEHOLDER
  pyradiomics_config_paths:
    - /home/das/QuantUS_Projs/QuantUS-Plugins-CEUS/configs/pyradiomics/moderate.yml
analysis_funcs:
  - pyradiomics

# Step 5: Curve quantification
curve_quant_function_names: ['first_order', 'wash_rates', 'lognormal_fit']
curve_quant_output_path: PLACEHOLDER
curve_quant_kwargs:
  curves_to_fit: 
    - moderate_diagnostics_Image-original_Mean
  n_frames_to_analyze: 1000
