# Example configuration for curve loading workflow
# This workflow loads pre-computed curves and performs quantification

# Curve loading configuration
curves_path: "/home/das/Downloads/TTC-Results/m904_m904d20150410BolusFull4D_m904d20150410BolusFull4DMasked_bolus_curves.csv"
curves_loader_type: "load_ttc_curves"
curves_loader_kwargs: {}

# Curve quantification configuration
output_path: "quantification_results.csv"
quantification_functions: []  # Empty list will use all available functions
curve_quant_kwargs:
  curves_to_fit: ['moderate_diagnostics_Image-original_Mean']
  n_frames_to_analyze: 100
