# Screen 1: Scan loader
scan_loader: nifti

# Screen 2: Scan inputs
scan_path: /Users/davidspector/Home/Stanford/QuantUS Projects/Sample Data/3D TJU-SHC CEUS/TJU-P01-V2-CEUS_12.32.11/TJU-P01-V2-CEUS_12.32.11_mf_sip_capture_50_2_1_0.raw_CEUS.nii.gz
scan_loader_kwargs:
  transpose: False

# Step 3: Image preprocessing
scan_preproc_funcs:
  - resample
scan_preproc_kwargs:
  target_vox_size: [1., 1., 1.]  # mm
  interp: linear

# Screen 4: Segmentation (either drawing or saved)
seg_path: /media/das/TOSHIBA EXT/P-Selectin Data/Feb VOIs (David)/20190216160924.918_segmentation_LEFT.nii.gz
seg_loader: nifti
seg_loader_kwargs:
  assert_scan: False
  assert_phantom: False

# Step 5: Segmentation preprocessing
seg_preproc_funcs: 
  - resample
seg_preproc_kwargs:
  target_vox_size: [1., 1., 1.]  # mm
  interp: nearest

# Screen 4: Analysis
analysis_type: curves_paramap
analysis_kwargs:
  curves_output_path: 
  ax_vox_ovrlp: 50  # %
  sag_vox_ovrlp: 50  # %
  cor_vox_ovrlp: 50  # %
  ax_vox_len: 3    # mm
  sag_vox_len: 3    # mm
  cor_vox_len: 3    # mm
analysis_funcs:
  - tic

# Step 5: Curve quantification
curve_quant_output_path: 
curve_quant_funcs:
  - lognormal_fit_select
curve_quant_kwargs:
  curves_to_fit:
    - TIC

# Step 6: Visualization
visualization_type: paramap
visualization_params: # Empty covers all parameters
custom_visualization_funcs: # N/A
  - plot_tics
visualization_kwargs:
  paramap_folder_path: paramaps_LOGNORMAL_DEMO_L_3
  hide_all_visualizations: False
