# Screen 1: Scan loader
scan_loader: nifti

# Screen 2: Scan inputs
scan_path: /Volumes/TOSHIBA EXT/P-Selectin Data/Feb 2019 Mice Batch 2/MouseBatch2D01_02162019/MouseC2M3_d001_02162019/20190216160924.918.nii.gz
scan_loader_kwargs:
  transpose: False
  resample_spacing: [0.70, 0.70, 0.70]  # mm

# Screen 3: Segmentation (either drawing or saved)
seg_path: /Volumes/TOSHIBA EXT/P-Selectin Data/Feb VOIs (David)/20190216160924.918_segmentation_LEFT.nii.gz
seg_loader: nifti_voi
seg_loader_kwargs:
  assert_scan: False
  assert_phantom: False

# Screen 4: Analysis
analysis_type: curves_paramap
analysis_kwargs:
  curves_output_path: 
  ax_vox_ovrlp: 50  # %
  sag_vox_ovrlp: 50  # %
  cor_vox_ovrlp: 50  # %
  ax_vox_len: 3    # mm
  sag_vox_len: 3    # mm
  cor_vox_len: 3    # mm
analysis_funcs:
  - tic

# Step 5: Curve quantification
curve_quant_output_path: 
curve_quant_funcs:
  - lognormal_fit_select
curve_quant_kwargs:
  curves_to_fit:
    - TIC

# Step 6: Visualization
visualization_type: paramap
visualization_params: # Empty covers all parameters
custom_visualization_funcs: # N/A
  - plot_tics
visualization_kwargs:
  paramap_folder_path: paramaps_LOGNORMAL_DEMO_L_3
  hide_all_visualizations: False
