# Screen 1: Scan loader
scan_loader: custom_dicom

# Screen 2: Scan inputs
scan_path: /home/das/Downloads/DICOM Sample 3/
scan_loader_kwargs:

# Step 3: Image preprocessing
scan_preproc_funcs:
  - resample
scan_preproc_kwargs:
  target_vox_size: [0.05, 0.05]  # mm
  interp: linear

# Screen 4: Segmentation (either drawing or saved)
seg_path: /home/das/Downloads/DICOM Sample 3/demo_seg.nii.gz
seg_loader: nifti
seg_loader_kwargs:

# Step 5: Segmentation preprocessing
seg_preproc_funcs: 
  - resample
seg_preproc_kwargs:
  target_vox_size: [0.05, 0.05]  # mm
  interp: nearest

# Screen 4: Analysis
analysis_type: curves_paramap
analysis_kwargs:
  curves_output_path: 
  ax_vox_ovrlp: 50  # %
  sag_vox_ovrlp: 50  # %
  ax_vox_len: 0.5    # mm
  sag_vox_len: 0.5    # mm
analysis_funcs:
  - tic

# Step 5: Curve quantification
curve_quant_output_path: 
curve_quant_funcs:
  - lognormal_fit_full
curve_quant_kwargs:
  curves_to_fit:
    - TIC

# Step 6: Visualization
visualization_type: paramap
visualization_params: # Empty covers all parameters
custom_visualization_funcs: # N/A
  - plot_tics
visualization_kwargs:
  paramap_folder_path: PARAMAP_RESULTS
  hide_all_visualizations: False
