# Screen 1: Scan loader
scan_loader: nifti

# Screen 2: Scan inputs
scan_path: /Volumes/TOSHIBA EXT/Animal Data/Compare Bubbles Raw Scans/CEUS-26152-1.nii.gz
scan_loader_kwargs:
  transpose: False
  resample_spacing: [1.63, 1.63, 1.63]  # mm

# Screen 3: Segmentation (either drawing or saved)
seg_path: /Volumes/TOSHIBA EXT/Animal Data/Compare Bubbles Raw Scans/v1_voi.nii.gz
seg_loader: nifti_voi
seg_loader_kwargs:
  assert_scan: False
  assert_phantom: False

# Screen 4: Analysis
analysis_type: curves_paramap
analysis_kwargs:
  curves_output_path: 
  ax_vox_ovrlp: 50  # %
  sag_vox_ovrlp: 50  # %
  cor_vox_ovrlp: 50  # %
  ax_vox_len: 20    # mm
  sag_vox_len: 20    # mm
  cor_vox_len: 20    # mm
analysis_funcs:
  - tic

# Step 5: Curve quantification
curve_quant_output_path: 
curve_quant_funcs:
  - lognormal_fit
curve_quant_kwargs:
  curves_to_fit:
    - TIC

# Step 6: Visualization
visualization_type: paramap
visualization_params: # Empty covers all parameters
custom_visualization_funcs: # N/A
visualization_kwargs:
  paramap_folder_path: paramaps_LOGNORMAL_CLI_DEMO
  hide_all_visualizations: False
