# Screen 1: Scan loader
scan_loader: nifti

# Screen 2: Scan inputs
scan_path: PLACEHOLDER
scan_loader_kwargs:
  transpose: False
  resample_spacing: [0.7, 0.37, 0.52]

# Screen 3: Segmentation (either drawing or saved)
seg_path: PLACEHOLDER
seg_loader: nifti_voi
seg_loader_kwargs:
  assert_scan: False
  assert_phantom: False

# Screen 4: Analysis
analysis_type: curves
analysis_kwargs:
  curves_output_path: PLACEHOLDER
  binwidth: 25
  min_intensity: 0
  pyradiomics_config_paths:
    - /home/das/QuantUS_Projs/QuantUS-Plugins-CEUS/configs/pyradiomics/moderate-pselectin.yml
analysis_funcs:
  - tic
  - pyradiomics

# Step 5: Curve quantification configuration
curve_quant_output_path: PLACEHOLDER
curve_quant_funcs:
  - auc_no_fit
  - dte
curve_quant_kwargs:
  tic_name: TIC