# Screen 1: Scan loader
scan_loader: nifti

# Screen 2: Scan inputs
scan_path: /media/das/TOSHIBA EXT/P-Selectin Data/Feb 2019 Mice Batch 2/MouseBatch2D01_02162019/MouseC2M3_d001_02162019/20190216160924.918.nii.gz
scan_loader_kwargs:
  transpose: False

# Step 3: Image preprocessing
scan_preproc_funcs:
  - resample
scan_preproc_kwargs:
  target_vox_size: [1., 1., 1.]  # mm
  interp: linear

# Screen 4: Segmentation (either drawing or saved)
seg_path: /media/das/TOSHIBA EXT/P-Selectin Data/Feb VOIs (David)/20190216160924.918_segmentation_LEFT.nii.gz
seg_loader: nifti_voi
seg_loader_kwargs:
  assert_scan: False
  assert_phantom: False

# Step 5: Segmentation preprocessing
seg_preproc_funcs: 
  - resample
seg_preproc_kwargs:
  target_vox_size: [1., 1., 1.]  # mm
  interp: nearest

# Screen 4: Analysis
analysis_type: curves
analysis_kwargs:
  curves_output_path: CURVES_DEMO.csv
  binwidth: 25 
  min_intensity: 0
  pyradiomics_config_paths:
    - /home/das/QuantUS_Projs/QuantUS-Plugins-CEUS/configs/pyradiomics/moderate.yml
analysis_funcs:
  - tic
  - pyradiomics
